<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PcRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class PcRepository extends EntityRepository
{
}
